//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.08 at 03:28:55 PM CET 
//


package userfunctions.functions.beans;

import java.math.BigDecimal;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for Person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Person"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PersonId" type="{http://rem.osplus/basis/151}TEXT"/&gt;
 *         &lt;element name="hauptantragstellerKz" type="{http://rem.osplus/basis/151}SVZ"/&gt;
 *         &lt;element name="PersonTyp" type="{http://rem.osplus/basis/151}SVZ"/&gt;
 *         &lt;element name="SchufaNK" type="{http://rem.osplus/basis/151}SVZ" minOccurs="0"/&gt;
 *         &lt;element name="SchufaNM" type="{http://rem.osplus/basis/151}SVZ" minOccurs="0"/&gt;
 *         &lt;element name="Obligation" type="{http://rem.osplus/basis/151}DEZIMALZAHL" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Person", propOrder = {
    "PersonId",
    "hauptantragstellerKz",
    "PersonTyp",
    "SchufaNK",
    "SchufaNM",
    "Obligation"
})
@Entity(name = "Person")
@Table(name = "PERSON")
@Inheritance(strategy = InheritanceType.JOINED)
public class Person
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected String personId;
    @XmlElement(required = true)
    protected String personTyp;
    protected String schufaNK;
    protected String schufaNM;
    protected BigDecimal obligation;

    /**
     * Gets the value of the PersonId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Id
    @Column(name = "PERSON_ID", length = 255)
    @GeneratedValue(strategy = GenerationType.AUTO)
    public String getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the PersonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonId(String value) {
        this.personId = value;
    }

    /**
     * Gets the value of the PersonTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PERSON_TYP", length = 255)
    public String getPersonTyp() {
        return personTyp;
    }

    /**
     * Sets the value of the PersonTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonTyp(String value) {
        this.personTyp = value;
    }

    /**
     * Gets the value of the SchufaNK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "SCHUFA_NK", length = 255)
    public String getSchufaNK() {
        return schufaNK;
    }

    /**
     * Sets the value of the SchufaNK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchufaNK(String value) {
        this.schufaNK = value;
    }

    /**
     * Gets the value of the SchufaNM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "SCHUFA_NM", length = 255)
    public String getSchufaNM() {
        return schufaNM;
    }

    /**
     * Sets the value of the SchufaNM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchufaNM(String value) {
        this.schufaNM = value;
    }

    /**
     * Gets the value of the Obligation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    @Basic
    @Column(name = "Obligation", precision = 20, scale = 10)
    public BigDecimal getObligation() {
        return obligation;
    }

    /**
     * Sets the value of the Obligation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setObligation(BigDecimal value) {
        this.obligation = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Person that = ((Person) object);
        {
            String lhsPersonId;
            lhsPersonId = this.getPersonId();
            String rhsPersonId;
            rhsPersonId = that.getPersonId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "PersonId", lhsPersonId), LocatorUtils.property(thatLocator, "PersonId", rhsPersonId), lhsPersonId, rhsPersonId)) {
                return false;
            }
        }
        {
            String lhsPersonTyp;
            lhsPersonTyp = this.getPersonTyp();
            String rhsPersonTyp;
            rhsPersonTyp = that.getPersonTyp();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "PersonTyp", lhsPersonTyp), LocatorUtils.property(thatLocator, "PersonTyp", rhsPersonTyp), lhsPersonTyp, rhsPersonTyp)) {
                return false;
            }
        }
        {
            String lhsSchufaNK;
            lhsSchufaNK = this.getSchufaNK();
            String rhsSchufaNK;
            rhsSchufaNK = that.getSchufaNK();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "SchufaNK", lhsSchufaNK), LocatorUtils.property(thatLocator, "SchufaNK", rhsSchufaNK), lhsSchufaNK, rhsSchufaNK)) {
                return false;
            }
        }
        {
            String lhsSchufaNM;
            lhsSchufaNM = this.getSchufaNM();
            String rhsSchufaNM;
            rhsSchufaNM = that.getSchufaNM();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "SchufaNM", lhsSchufaNM), LocatorUtils.property(thatLocator, "SchufaNM", rhsSchufaNM), lhsSchufaNM, rhsSchufaNM)) {
                return false;
            }
        }
        {
            BigDecimal lhsObligation;
            lhsObligation = this.getObligation();
            BigDecimal rhsObligation;
            rhsObligation = that.getObligation();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "Obligation", lhsObligation), LocatorUtils.property(thatLocator, "Obligation", rhsObligation), lhsObligation, rhsObligation)) {
                return false;
            }
        }

        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String thePersonId;
            thePersonId = this.getPersonId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "PersonId", thePersonId), currentHashCode, thePersonId);
        }
        {
            String thePersonTyp;
            thePersonTyp = this.getPersonTyp();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "PersonTyp", thePersonTyp), currentHashCode, thePersonTyp);
        }
        {
            String theSchufaNK;
            theSchufaNK = this.getSchufaNK();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "SchufaNK", theSchufaNK), currentHashCode, theSchufaNK);
        }
        {
            String theSchufaNM;
            theSchufaNM = this.getSchufaNM();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "SchufaNM", theSchufaNM), currentHashCode, theSchufaNM);
        }
        {
            BigDecimal theObligation;
            theObligation = this.getObligation();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "Obligation", theObligation), currentHashCode, theObligation);
        }

        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
